### ISSUE TITLE
Potential modification to source code for overlap plot

### ISSUE THREAD

**Issue by bsharris381** [mlysy/nicheROVER#1]
Hi,

The nicheROVER package worked great for a recent project that I'm writing up.  However, I have a question about modifying the source code for the overlap.plot to generate two plots (each represents a different habitat) that have the same number of rows and columns even though one graph would have six species and the other graph only three species.  I'm looking to combine two overlap plots into a single figure with two panels (one column, two rows) for a nice comparison. In this case, it would be a comparison of the three species that are found in both plots, although I'd like to retain the information on the three other species because it is still of interest.  Is there any way to maintain the same 6 x 6 structure to the plot but only have data for three species? 

Any thoughts would be appreciated!  I'm worried about going in and attempting to modify the source code for this function and possibly (more like probably) doing something wrong that causes incorrect estimates for some reason.

Thank you,

Brandon

**Comment by benjaminhlina** [comment]
Hi @bsharris381 I have created a blog post where you can extract the data to plot in ggplot giving you more flexibility in the plot structure ect. I hope it is helpful. 
https://blog.benjaminhlina.com/posts/post-with-code/nicheROVER-ggplot/nicheROVER_ggplot.html

**Comment by mlysy** [comment]
Switching over to ggplot is the way to go!  `niw.post()`, `overlap()`, etc. return all the data that is used in `niche.plot()`, `overlap.plot()`, etc, and @benjaminhlina's post shows how to set up equivalent plots with ggplot, which you can then customize as desired.
