### ISSUE TITLE
new package `{nichetools}`

### ISSUE THREAD

**Issue by benjaminhlina** [mlysy/nicheROVER#4]
Hi @mlysy, 

I wanted to share with you that I have created some functions and compiled them into a package, [{nichetools}](https://benjaminhlina.github.io/nichetools/index.html), centred on the walkthrough I made last year for the package. Thought you might be interested in seeing the work/updating the link to the blog - no worries if not just thought you might be interested. Thanks again along with the rest of the team that worked on putting together `{nicheROVER}` and publishing how it works as it's a great package for working with stable isotope data. 

Thanks,
Ben

**Comment by mlysy** [comment]
Thanks for the heads-up!
